"""Export helpers for classroom and demo reports."""

from __future__ import annotations

import csv
import html
import io
import time

from .models import AnalysisResult, ClauseFinding
from .negotiation import build_benchmark, build_checklist
from .summarizer import build_verdict


def findings_to_rows(findings: list[ClauseFinding]) -> list[dict[str, str | int | float]]:
    return [
        {
            "Clause": finding.title,
            "Category": finding.category,
            "Risk": finding.severity,
            "Confidence": round(finding.confidence, 2),
            "Matched Terms": ", ".join(finding.matched_terms),
            "Red Flags": ", ".join(finding.red_flags),
            "Recommendation": finding.recommendation,
            "Evidence": finding.snippet,
        }
        for finding in findings
    ]


def findings_csv(findings: list[ClauseFinding]) -> str:
    output = io.StringIO()
    rows = findings_to_rows(findings)
    writer = csv.DictWriter(output, fieldnames=list(rows[0].keys()) if rows else ["Clause"])
    writer.writeheader()
    writer.writerows(rows)
    return output.getvalue()


def negotiation_markdown(analysis: AnalysisResult) -> str:
    """Plain-text / Markdown negotiation pack for paste-into-email use."""

    checklist = build_checklist(analysis.findings)
    risk = analysis.risk
    verdict = build_verdict(risk)

    lines: list[str] = [
        "# ClearClause Negotiation Pack",
        "",
        f"**Document:** {analysis.document.filename}",
        f"**Risk score:** {risk.score}/100 ({risk.label})",
        f"**Verdict:** {verdict.one_liner}",
        "",
        "## Priority negotiation actions",
        "",
    ]
    if not checklist:
        lines.append("- No actionable high or medium-severity items were detected.")
    for item in checklist:
        lines.append(f"### {item.priority}. {item.title}  ·  {item.severity}")
        lines.append(f"_{item.rationale}_")
        for action in item.actions:
            lines.append(f"- [ ] {action}")
        lines.append("")

    lines.append("## Discovery questions to send the other party")
    from .negotiation import suggested_questions

    for question in suggested_questions(analysis, limit=6):
        lines.append(f"- {question}")
    lines.append("")
    lines.append("_Generated by ClearClause — educational output, not legal advice._")
    return "\n".join(lines)


def build_html_report(analysis: AnalysisResult) -> str:
    doc = analysis.document
    risk = analysis.risk
    verdict = build_verdict(risk)
    generated = time.strftime("%Y-%m-%d %H:%M")

    findings_html = "\n".join(_finding_row(f) for f in analysis.findings) or _empty_row()
    flag_items = (
        "".join(f"<li>{html.escape(flag)}</li>" for flag in risk.top_flags)
        or "<li>No high-severity priority flags detected.</li>"
    )

    checklist = build_checklist(analysis.findings)
    if checklist:
        checklist_html = "".join(_checklist_block(item) for item in checklist)
    else:
        checklist_html = (
            '<p class="empty">No actionable high or medium-severity items were detected.</p>'
        )

    benchmark = build_benchmark(analysis.findings)
    benchmark_html = "".join(_benchmark_row(row) for row in benchmark) or _empty_row(cols=5)

    dim_rows = "".join(
        f"<tr><td>{html.escape(name)}</td><td><div class='bar'>"
        f"<span style='width:{value}%; background:{_dim_color(value)}'></span></div></td>"
        f"<td>{value}/100</td></tr>"
        for name, value in risk.dimension_scores.items()
    )

    summary_html = html.escape(analysis.summary_markdown).replace("\n", "<br>")

    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>ClearClause Contract Risk Report — {html.escape(doc.filename)}</title>
  <style>
    :root {{
      --ink: #0f1d18; --muted: #5a6a62; --paper: #f7f7f1; --soft: #fbfbf6;
      --line: #e3e6dd; --forest: #1f3a2d; --forest-bright: #2f5a40;
      --coral: #c2410c; --coral-soft: #fee4d6;
      --amber: #b45309; --amber-soft: #fdf3c6;
      --green: #15803d; --green-soft: #d6f0df;
      --blue: #1d4ed8; --blue-soft: #dbeafe;
    }}
    * {{ box-sizing: border-box; }}
    body {{
      margin: 0;
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Inter, sans-serif;
      color: var(--ink);
      background: var(--paper);
    }}
    main {{ max-width: 1100px; margin: 0 auto; padding: 28px 24px 48px 24px; }}
    .hero {{
      background: linear-gradient(135deg, #142a20 0%, #1f3a2d 55%, #2f5a40 100%);
      color: #f6f5ec;
      border-radius: 16px;
      padding: 28px 30px;
      box-shadow: 0 16px 36px rgba(15,29,24,.12);
    }}
    .hero .brand {{
      font-family: "Iowan Old Style", "Source Serif 4", serif;
      font-weight: 800;
      font-size: 30px;
      letter-spacing: -0.01em;
    }}
    .hero .tag {{
      text-transform: uppercase;
      letter-spacing: .14em;
      font-size: 12px;
      color: rgba(246,245,236,.72);
      margin-top: 4px;
    }}
    .hero .meta {{
      margin-top: 18px;
      color: rgba(246,245,236,.85);
      font-size: 14px;
    }}
    .hero .meta strong {{ color: #f6f5ec; }}

    .score-strip {{
      display: grid;
      grid-template-columns: repeat(4, 1fr);
      gap: 12px;
      margin-top: 18px;
    }}
    .tile {{
      background: #ffffff;
      border: 1px solid var(--line);
      border-radius: 12px;
      padding: 14px 16px;
      box-shadow: 0 1px 2px rgba(15,29,24,.04);
    }}
    .tile .label {{
      font-size: 11px; letter-spacing: .14em; text-transform: uppercase;
      color: var(--muted); font-weight: 600;
    }}
    .tile .value {{
      font-family: "Iowan Old Style", "Source Serif 4", serif;
      font-weight: 800;
      font-size: 28px; line-height: 1.1; margin-top: 2px;
    }}
    .tile.coral .value {{ color: var(--coral); }}
    .tile.amber .value {{ color: var(--amber); }}
    .tile.green .value {{ color: var(--green); }}
    .tile.forest .value {{ color: var(--forest-bright); }}

    .verdict {{
      margin-top: 22px;
      background: #ffffff;
      border: 1px solid var(--line);
      border-left: 6px solid {_verdict_color(verdict.css_class)};
      border-radius: 14px;
      padding: 18px 22px;
      box-shadow: 0 1px 2px rgba(15,29,24,.04);
    }}
    .verdict .label {{
      font-size: 11px; letter-spacing: .14em; text-transform: uppercase;
      color: var(--muted); font-weight: 600;
    }}
    .verdict .line {{
      font-family: "Iowan Old Style", "Source Serif 4", serif;
      font-weight: 700;
      font-size: 22px; margin: 4px 0 6px 0;
    }}
    .verdict p {{ color: var(--muted); margin: 0; line-height: 1.55; font-size: 14px; }}

    h2 {{
      font-family: "Iowan Old Style", "Source Serif 4", serif;
      font-weight: 700;
      font-size: 22px;
      margin: 28px 0 12px 0;
      letter-spacing: -0.01em;
    }}
    .panel {{
      background: #fff;
      border: 1px solid var(--line);
      border-radius: 14px;
      padding: 18px 22px;
      box-shadow: 0 1px 2px rgba(15,29,24,.04);
    }}
    ul {{ margin: 0; padding-left: 18px; }}
    ul li {{ margin-bottom: 6px; line-height: 1.5; }}

    .checklist-card {{
      background: #fff; border: 1px solid var(--line); border-left: 5px solid var(--forest-bright);
      border-radius: 12px; padding: 14px 16px; margin-bottom: 10px;
      box-shadow: 0 1px 2px rgba(15,29,24,.04);
    }}
    .checklist-card.HIGH {{ border-left-color: var(--coral); }}
    .checklist-card.MEDIUM {{ border-left-color: var(--amber); }}
    .checklist-card .header {{
      display: flex; align-items: center; justify-content: space-between; gap: 12px;
      font-family: "Iowan Old Style", "Source Serif 4", serif;
      font-weight: 700; font-size: 16px;
    }}
    .checklist-card .rationale {{ color: var(--muted); font-size: 13px; margin: 4px 0 6px 0; }}
    .badge {{
      display: inline-block; padding: 2px 8px; border-radius: 999px;
      font-size: 10px; font-weight: 700; letter-spacing: .06em; text-transform: uppercase;
    }}
    .badge.HIGH {{ background: var(--coral-soft); color: var(--coral); }}
    .badge.MEDIUM {{ background: var(--amber-soft); color: var(--amber); }}
    .badge.LOW {{ background: var(--green-soft); color: var(--green); }}
    .badge.INFO {{ background: var(--blue-soft); color: var(--blue); }}

    table {{
      width: 100%; border-collapse: collapse; background: white;
      border-radius: 14px; overflow: hidden;
      box-shadow: 0 1px 2px rgba(15,29,24,.04); border: 1px solid var(--line);
    }}
    th, td {{ padding: 10px 14px; border-bottom: 1px solid var(--line); vertical-align: top; text-align: left; font-size: 13px; }}
    th {{
      background: #f1efe6; font-weight: 700;
      letter-spacing: .04em; text-transform: uppercase; font-size: 11px;
    }}
    tr:last-child td {{ border-bottom: none; }}

    .dim-table .bar {{
      width: 100%; height: 10px; background: #eef0e8; border-radius: 999px; overflow: hidden;
    }}
    .dim-table .bar span {{ display: block; height: 100%; }}

    .bench-status {{
      display: inline-block; padding: 2px 8px; border-radius: 999px;
      font-size: 10px; font-weight: 700; letter-spacing: .06em; text-transform: uppercase;
    }}
    .bench-status.fair {{ background: var(--green-soft); color: var(--green); }}
    .bench-status.concerning {{ background: var(--amber-soft); color: var(--amber); }}
    .bench-status.high-risk {{ background: var(--coral-soft); color: var(--coral); }}
    .bench-status.missing {{ background: var(--blue-soft); color: var(--blue); }}

    .empty {{ color: var(--muted); font-size: 13px; }}
    footer {{ margin-top: 28px; color: var(--muted); font-size: 12px; text-align: center; }}
    @media print {{
      .stApp, body {{ background: white; }}
      .hero {{ box-shadow: none; }}
      .panel, .checklist-card, table, .verdict, .tile {{ box-shadow: none; break-inside: avoid; }}
    }}
  </style>
</head>
<body>
<main>
  <section class="hero">
    <div class="brand">ClearClause</div>
    <div class="tag">Contract risk report</div>
    <div class="meta">
      <strong>Document:</strong> {html.escape(doc.filename)}
      &nbsp;·&nbsp; <strong>Words:</strong> {doc.word_count}
      &nbsp;·&nbsp; <strong>Generated:</strong> {generated}
    </div>
    <div class="score-strip">
      <div class="tile" style="color:{_verdict_color(verdict.css_class)};">
        <div class="label">Risk score</div>
        <div class="value" style="color:{_verdict_color(verdict.css_class)};">{risk.score}/100</div>
      </div>
      <div class="tile coral"><div class="label">High</div><div class="value">{risk.high_count}</div></div>
      <div class="tile amber"><div class="label">Medium</div><div class="value">{risk.medium_count}</div></div>
      <div class="tile green"><div class="label">Low</div><div class="value">{risk.low_count}</div></div>
    </div>
  </section>

  <div class="verdict {verdict.css_class}">
    <div class="label">ClearClause verdict</div>
    <div class="line">{html.escape(verdict.label)} — {html.escape(verdict.one_liner)}</div>
    <p>{html.escape(verdict.body)}</p>
  </div>

  <h2>Executive summary</h2>
  <div class="panel">{summary_html}</div>

  <h2>Risk by business area</h2>
  <div class="panel">
    <table class="dim-table">
      <thead><tr><th>Area</th><th>Concentration</th><th>Score</th></tr></thead>
      <tbody>{dim_rows}</tbody>
    </table>
  </div>

  <h2>Priority flags</h2>
  <div class="panel"><ul>{flag_items}</ul></div>

  <h2>Negotiation checklist</h2>
  {checklist_html}

  <h2>Fair-contract benchmark</h2>
  <table>
    <thead>
      <tr><th>Clause</th><th>Status</th><th>Fair standard</th><th>Detected in this contract</th><th>Gap</th></tr>
    </thead>
    <tbody>{benchmark_html}</tbody>
  </table>

  <h2>Detected clauses</h2>
  <table>
    <thead><tr><th>Clause</th><th>Risk</th><th>Confidence</th><th>Plain English</th><th>Recommendation</th></tr></thead>
    <tbody>{findings_html}</tbody>
  </table>

  <footer>
    ClearClause is an educational NLP project. Output is not legal advice.<br>
    Pipeline: regex pattern matching + TF-IDF semantic similarity + extractive retrieval Q&amp;A.
  </footer>
</main>
</body>
</html>"""


def _verdict_color(css_class: str) -> str:
    return {
        "CRITICAL": "#9a1b0a",
        "HIGH": "#c2410c",
        "REVIEW": "#b45309",
        "LOW": "#15803d",
    }.get(css_class, "#1f3a2d")


def _dim_color(value: int) -> str:
    if value >= 70:
        return "#c2410c"
    if value >= 45:
        return "#b45309"
    if value >= 20:
        return "#2f5a40"
    return "#6f8d5c"


def _finding_row(finding: ClauseFinding) -> str:
    return (
        "<tr>"
        f"<td><strong>{html.escape(finding.title)}</strong><br>"
        f"<small style='color:#5a6a62'>{html.escape(finding.category or finding.section_title)}</small></td>"
        f"<td><span class='badge {finding.severity}'>{finding.severity}</span></td>"
        f"<td>{finding.confidence:.0%}</td>"
        f"<td>{html.escape(finding.plain_english)}</td>"
        f"<td>{html.escape(finding.recommendation)}</td>"
        "</tr>"
    )


def _checklist_block(item) -> str:
    actions = "".join(f"<li>{html.escape(action)}</li>" for action in item.actions)
    return (
        f"<div class='checklist-card {item.severity}'>"
        f"<div class='header'><span>#{item.priority} · {html.escape(item.title)}</span>"
        f"<span class='badge {item.severity}'>{item.severity}</span></div>"
        f"<div class='rationale'>{html.escape(item.rationale)}</div>"
        f"<ul>{actions}</ul></div>"
    )


def _benchmark_row(row) -> str:
    return (
        "<tr>"
        f"<td><strong>{html.escape(row.title)}</strong><br>"
        f"<small style='color:#5a6a62'>{html.escape(row.category)}</small></td>"
        f"<td><span class='bench-status {row.status}'>{row.status}</span></td>"
        f"<td>{html.escape(row.fair_standard)}</td>"
        f"<td>{html.escape(row.detected_text)}</td>"
        f"<td>{html.escape(row.gap)}</td>"
        "</tr>"
    )


def _empty_row(cols: int = 5) -> str:
    return (
        f"<tr><td colspan='{cols}' style='text-align:center;color:#5a6a62'>"
        "No rows to display."
        "</td></tr>"
    )
